### ISSUE TITLE
Broken link to 2013 workshop in Dundee

### ISSUE THREAD

**Issue by alex-konovalov** [swcarpentry/site#1022]
The map of previous workshops at http://software-carpentry.org/workshops/previous.html points to the workshop in Dundee in 2013 but http://davidmam.github.io/2013-12-16-dundee/ seems to be no longer available.

**Comment by jduckles** [comment]
Repo is still there https://github.com/davidmam/2013-12-16-dundee not sure why it isn't working. Can't fix it on our end so closing.
