### ISSUE TITLE
Misplaced workshop location: Liverpool 2014

### ISSUE THREAD

**Issue by alex-konovalov** [swcarpentry/site#1023]
The picture says it all :)
![screen shot 2015-07-14 at 13 32 51](https://cloud.githubusercontent.com/assets/5751387/8673279/ff574c9c-2a2c-11e5-8faa-2c7f871b6456.png)

**Comment by r-gaia-cs** [comment]
@alex-konovalov Do you know the correct latitude and longitude to be used? We get this information from https://github.com/kkwakwa/2014-11-17-liverpool/blob/gh-pages/index.html.

**Comment by alex-konovalov** [comment]
Thanks. It looks like the minus is missing there in the line `latlng: 53.4087914,2.9723748`

**Comment by jduckles** [comment]
@kkwakwa has fixed this.
