### ISSUE TITLE
/bootcamp/ URL no longer resolves - could it be redirected to /workshops/ ?

### ISSUE THREAD

**Issue by ndjones** [swcarpentry/site#1040]
I was browsing the SSI website (and I'm sure there are others) and noticed they point to http://software-carpentry.org/bootcamps/, which is no longer valid.

Perhaps a redirect could be created to resolve this URL to http://software-carpentry.org/workshops ?

**Comment by gvwilson** [comment]
Raniere, can you please magic this?

**Comment by rgaiacs** [comment]
> Raniere, can you please magic this?

Magic done at #1041.
