### ISSUE TITLE
Requesting a workshop

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/site#1062]
Is there a reason why the workshop request can come in through the form or a regular email?
On https://software-carpentry.org/workshops/index.html:

> Want Us to Teach Where You Are? Please fill in this form or mail us.

It would make it a lot easier to keep track of bootcamp requests if they all came in only through the form.

**Comment by rgaiacs** [comment]
> Is there a reason why the workshop request can come in through the form or a regular email?

People that already host one workshop sometimes request another one by email.

> It would make it a lot easier to keep track of bootcamp requests if they all came in only through the form.

I'm +1 for that.

**Comment by gvwilson** [comment]
+1 to form only, though I suspect people will still email us.  Make the 
switch as soon as AMY supports direct submission?

**Comment by jduckles** [comment]
@maneesha can this be closed?
