### ISSUE TITLE
Workshop fee for for-profit institutions

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/site#1063]
It's not clear what the two fee levels are.  From
https://software-carpentry.org/workshops/request.html

> If you are a for-profit institution, such as a company, the fees are US$5000 and US$3000 respectively, of which three quarters is used to underwrite workshops at institutions that could otherwise not afford them.

**Comment by jiffyclub** [comment]
That should match the first-in-a-year/subsequent workshops phrasing in the first bullet: " this is presently US$1250 for the first worskhop at an institution in any given year, and US$750 for each subsequent workshop in that year at that institution."

But I think we're about to stop having that structure and have all workshops cost the same.

**Comment by rgaiacs** [comment]
> But I think we're about to stop having that structure and have all workshops cost the same.

We will keep until the end of 2015 the "this is presently US$1250 for the first worskhop at an institution in any given year, and US$750 for each subsequent workshop in that year at that institution" for institutions that already paid for at least one workshop at 2015.
