### ISSUE TITLE
Asking requesters of  workshops about paying the fee

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/site#1066]
Current question:

> My institution will cover instructors' travel and accommodation costs, and I understand the Software Carpentry Foundation's administrative fee 

Can we break this out into two questions, one for our admin fee and one for covering travel/accommodations? We have some hosts who can do our admin fee but not instructor travel.

**Comment by gvwilson** [comment]
@pbanaszkiewicz This should be included when we shift workshop requests 
to AMY.

**Comment by pbanaszkiewicz** [comment]
I accidentally broke this question into two in the mockups and I'm going to implement it this way as soon as I get over this issue: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-August/000145.html

**Comment by jduckles** [comment]
@maneesha, is this solved in AMY now? If so can you please close.

**Comment by pbanaszkiewicz** [comment]
It's solved (see https://amy.software-carpentry.org/workshops/swc/request/), but I have no power to close this issue.
