### ISSUE TITLE
Make biblio stomps on bib.html

### ISSUE THREAD

**Issue by andreww** [swcarpentry/site#1074]
About half way down bib.html (at the "Research in Computational Science and Software Engineering" heading) there is a comment:
        
        

and (if software-carpentry.bib will compile) running `make biblio` does regenerate the list of papers below this heading. However, it also overwrites `bib/bib.html` resulting in everything above this point (the recommended reading) being removed. I guess the recommended reading was added at some point to make a nicer page without noticing the auto-generated nature of the page. This probably means that the long list below this point never gets updated. 

I think there are two possible fixes:
1. Have pages, one for the recommended reading and one for the content of software-carpentry.bib
2. Have everything on one page, but make it possible to auto-generate the stuff from software-carpentry.bib without stomping over everything else.

In either case, I think the first step is to separate out the end of the document and get it into a state where it can be created from software-carpentry.bib. At this point we can use git to tell us if there are any changes in bib.html that should be made to software-carpentry.bib before proceeding further. We can then either add links to make (1) work or (presumably) do some jekyll magic to make the document appear inside bib.html to make (2) work.

Thoughts? I can do most of this, but I'm not sure about the jekyll if this is the last step. Would we would need to put the file to include inside _include?

**Comment by gvwilson** [comment]
I think splitting recommended reading from the auto-generated bib.html 
is the cleanest and most morally defensible solution.

**Comment by andreww** [comment]
Closed by #1075
