### ISSUE TITLE
What provenance tools do you use?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#1085]
What do people on this list currently use to  track the provenance of their original data sets and their intermediate and final results?  How well does it work across languages?  How easy was it to learn, and how much effort does it take day-to-day?

1. [Original question](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-September/003319.html)
2. [Response about Sumatra](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-September/003320.html)
3. [Another response](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-September/003322.html)
4. [Response asking what people use](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-September/003321.html)
5. [Discussion from 2012](http://software-carpentry.org/blog/2012/10/wanted-an-entry-level-provenance-library.html)

**Comment by btel** [comment]
For a couple of years I used [sumatra](https://pythonhosted.org/Sumatra/) (I was also one of the developer at that time). Sumatra works well with most python and non-python projects, especially when you can separate the code, parameters and data into different files. The main drawback was that it did not have by default a fine-grained support for running indvidual steps of larger workflows (in make-like fashion). 

My current setup uses git. I store code, parameters and the results (just figures no intermediate results) in a single git repository (I use submodules for externally-developed libraries). The drawback of this setup is that it does not track the system libraries and data. It is not fully automatic requires also some more care (and effort) to keep everything in sync. I found that it was a good trade-off between extra work and the ability to reproduce all results of previous analyses.

**Comment by robintw** [comment]
Greg just contacted me and suggested that I might want to participate in this discussion, as I've been discussing another provenance tool with him (a Software Carpentry blog post will be coming shortly).

The tool is called [recipy](https://github.com/recipy/recipy) and is described in more detail in my blog [post](http://blog.rtwilson.com/introducing-recipy-effortless-provenance-tracking-with-python/). It's Python-only at the moment, and uses low-level hooks in Python to capture all input and output, as well as lots of information about the environment. Unlike many other tools (eg. sumatra, and - it seems - noWorkflow), it doesn't require scripts to be run through another tool, it can work just
by placing 'import recipy' at the top of the code.

I presented this recently at EuroSciPy 2015 (video should be coming soon), and people seemed quite keen on it.

If anyone has any feedback on this tool, or would like to discuss it more, then I'd be very keen to hear your ideas. I've always thought that provenance tracking should come somewhere in the SWC syllabus, but it hasn't happened yet... Hopefully the development of tools like sumatra, noWorkflow and recipy will help make this easier to teach, and easier for general scientists to use.

**Comment by DamienIrving** [comment]
My capstone example for Data Management in the Weather and Climate Sciences teaches a simple method for recording provenance that doesn't require any formal tools (only the ability to write command line programs):
http://damienirving.github.io/capstone-oceanography/03-data-provenance.html

**Comment by IanHawke** [comment]
After Robin introduced me to recipy I got to thinking how this might be done with a legacy production code I use (https://einsteintoolkit.org/), and what I'd actually want to reproduce, which led to this proof-of-principle code:
https://github.com/IanHawke/im2sim

In short: docker containers for the code with standardized Makefile entrypoints, metadata identifying the containers on dockerhub.

**Comment by emhart** [comment]
Another tool for capturing workflows is recordr (https://github.com/NCEAS/recordr)  I'm sure @mbjones or @sbpcs59 could chime in with more specific details about the project if you're interested.

**Comment by psteinb** [comment]
for completeness ... people on the mailing list also suggested:
https://github.com/gems-uff/noworkflow
http://xonsh.org/tutorial_hist.html
