### ISSUE TITLE
SWC Instructor & Helper Retreat Page

### ISSUE THREAD

**Issue by BillMills** [swcarpentry/site#1087]
Hey folks - the mentorship committee is pulling together the Instructor & Helper Retreat event, and I'd like to add a page to the SWC website providing details (map of sites, broadcast talks, connection details, etc etc).

Happy to hammer this out myself, but before I do, are there any objections / gotchas / suggestions on this topic?

cc @ttimbers @gvwilson @noamross

**Comment by rgaiacs** [comment]
@ttimbers Could you inform us the date from the doodle poll?

**Comment by ttimbers** [comment]
The date the most people (67) could participate on is Sat. Nov 7.

Cheers,
Tiffany

**Comment by gvwilson** [comment]
Ouch - I can't do Nov 7.  But I can do Nov 14, which is almost as popular...

**Comment by ttimbers** [comment]
Let's do it on the 14th then.

On Sun, Sep 13, 2015 at 9:56 PM, Greg Wilson <notifications@github.com>
wrote:

> Ouch - I can't do Nov 7. But I can do Nov 14, which is almost as popular...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/site/issues/1087#issuecomment-139961430>.
>



-- 
Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by gvwilson** [comment]
Thanks - time to put together the blog post?

**Comment by jiffyclub** [comment]
Would it be better to do the page as a separate repo + gh-pages as for workshops? You'll be able to iterate a lot faster that way without relying on Greg to rebuild the website every time you make an update. We can make a repo and team for this in the SWC GitHub org so that it shows up at swcarpentry.github.io.

**Comment by ttimbers** [comment]
* Blog post is in the works (and close to finished) by @BillMills 
* @jiffyclub I think that sounds like a good idea, thanks!

**Comment by jiffyclub** [comment]
How does instructor-retreat-2015 sound for the repo name, and who should be on the team?

**Comment by BillMills** [comment]
The name sounds good; for team members, it should be me and @ttimbers at a bare minimum, but all are welcome to jump on board too.

**Comment by jiffyclub** [comment]
https://github.com/swcarpentry/instructor-retreat-2015

I think you and @ttimbers should be able to add people to the [team](https://github.com/orgs/swcarpentry/teams/instructor-retreat-2015), but not 100% sure. I can add people if necessary.

**Comment by gvwilson** [comment]
+1 to the repo name, and please add me to the team - thanks much.

**Comment by maneesha** [comment]
please add me too. thx.

**Comment by rgaiacs** [comment]
> Let's do it on the 14th then.
>
> Blog post is in the works (and close to finished) by @BillMills 

Thanks. :sparkling_heart:

**Comment by BillMills** [comment]
Cool, thanks all - let's close out here and move this conversation over to the [new repo](https://github.com/swcarpentry/instructor-retreat-2015).
