### ISSUE TITLE
Some links on instructors' checklist don't work

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/site#1090]
Links pointing to the Teaching Guide on instructors' checklist don't work: http://software-carpentry.org/workshops/checklists/instructors.html

**Comment by arokem** [comment]
Looks to me like anything with a `http://software-carpentry.org/v5` prefix is not there.

**Comment by gvwilson** [comment]
Can you give me an example to check?

On 2015-09-17 6:03 PM, Ariel Rokem wrote:
>
> Looks to me like anything with a |http://software-carpentry.org/v5| 
> prefix is not there.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/1090#issuecomment-141150990>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by arokem** [comment]
http://software-carpentry.org/v5/novice/teaching/index.html

**Comment by arokem** [comment]
Is this the same thing as https://github.com/swcarpentry/workshop-template/issues/242 ?

**Comment by gvwilson** [comment]
closed by #1093
