### ISSUE TITLE
Readme contains inaccurate instructions for adding an upcoming workshop to the website 

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/site#1094]
`config/workshop_urls.yml` no longer exists (unless I'm being daft and missed something?)

**Comment by gvwilson** [comment]
Good catch - we just moved to a new system where we get data about 
workshops from an online database tool.  I'll update these instructions. 
cc @pbanaszkiewicz

On 2015-09-19 4:04 AM, Naupaka Zimmerman wrote:
>
> |config/workshop_urls.yml| no longer exists (unless I'm being daft and 
> missed something?)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/1094>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
