### ISSUE TITLE
Summer Program from CNPEM

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/site#1098]
@gvwilson can we advertise http://pages.cnpem.br/bolsasdeverao/ ? Maybe that way we get one new instructor in South America + Caribbean.

**Comment by gvwilson** [comment]
Can you give us more background on who they are, what the event is, and 
how they're connected with SWC?

**Comment by rgaiacs** [comment]
You can think of CNPEM as the Brazilian national version of CERN. Is a summer program, like the one CERN has, https://webfest.web.cern.ch/.

I'm trying to find who is the responsible for the summer program to offer one workshop. Let keep this issue open for two weeks to remember me of it (the applications will be open until begin of November).
