### ISSUE TITLE
Outdated pricing information

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/site#1104]
On this page:
http://software-carpentry.org/scf/workshops.html
pricing data has not been updated.

There's a lot that needs to change on this page so I don't want to submit a PR without some discussion. (At minimum sections 3.5, 3.6, 4)

Also the blog post here:
http://software-carpentry.org/blog/2015/07/changes-to-admin-fee.html

does not include all the pricing information on this page:
http://software-carpentry.org/workshops/request.html

adding to potential confusion.

**Comment by gvwilson** [comment]
Good catch - I'll fix tomorrow.
