### ISSUE TITLE
Map on the team page not working :(

### ISSUE THREAD

**Issue by timtomch** [swcarpentry/site#1106]
Hi there

Is it just me or are instructors no longer appearing on the map above the "Our Team" page?
https://software-carpentry.org/pages/team.html

Thomas

**Comment by gvwilson** [comment]
*sigh* You're right, they've disappeared.  Dunno why.  I'll fix.

**Comment by gvwilson** [comment]
Try now?  May have been an interrupted/failed build.

**Comment by timtomch** [comment]
Working again. Thanks for the quick fix.
