### ISSUE TITLE
Update data for map of instructors

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/site#1118]
I don't know why Francisco Palm isn't listed on the map.

![screen shot 2015-10-08 at 10 25 33](https://cloud.githubusercontent.com/assets/1506457/10367440/e6521688-6da6-11e5-878d-c7ac4ac3ccca.png)

There should be one circle in Venezuela.

**Comment by gvwilson** [comment]
Because he hasn't yet filled in the information form in AMY, so his 
airport isn't in the database.

On 2015-10-08 2:26 PM, Raniere Silva wrote:
>
> Assigned #1118 <https://github.com/swcarpentry/site/issues/1118> to 
> @gvwilson <https://github.com/gvwilson>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/1118#event-430300893>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
