### ISSUE TITLE
Some country flags not shown correctly in "Future Workshops" table

### ISSUE THREAD

**Issue by jlehtoma** [swcarpentry/site#1119]
At least the Finnish flag in no shown correctly in  in [Future Workshops](http://software-carpentry.org/workshops/index.html#future) table. URL to the correct flag png seems to be wrong:
```
<img src="../img/flags/16/.png" title="" alt="" />
```
where it should be 
```
<img src="../img/flags/16/fi.png" title="fi" alt="fi" />
```
so it looks like the country shortcode is not properly generated. I'm not sure which part of the preprocessing turns the harvested country name (e.g. "Finland", from [our index.html](https://github.com/cbig/2015-11-25-helsinki/blob/gh-pages/index.html#L6)?) into a shortcode (e.g. "fi").

**Comment by gvwilson** [comment]
Hi Joona,

Can you change the 'country:' field to 'fi' (2-letter shortcode)?

Thanks,
Greg

**Comment by jlehtoma** [comment]
Hi Greg,

Thanks for looking into this. I [changed](https://github.com/cbig/2015-11-25-helsinki/commit/2cb76a4a6f9c4d41a7ac7c819eab3358c19b8547) the 'country' field into 'fi' in our site `_config.yml` and pushed the changes, should be live already.

**Comment by gvwilson** [comment]
Hm - Finland's flag still not showing up.  Investigating...

**Comment by gvwilson** [comment]
Ah - found it.  Should be OK in the next build.

On 2015-10-12 12:22 PM, Joona Lehtomäki wrote:
>
> Hi Greg,
>
> Thanks for looking into this. I changed 
> <https://github.com/cbig/2015-11-25-helsinki/commit/2cb76a4a6f9c4d41a7ac7c819eab3358c19b8547> 
> the 'country' field into 'fi' in our site |_config.yml| and pushed the 
> changes, should be live already.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/1119#issuecomment-147368887>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by jlehtoma** [comment]
Confirmed, Finland's flag is now shown correctly so I'm closing the issue. Thanks!
