### ISSUE TITLE
workshops not showing up on map/calendar

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/site#1130]
On page 

https://software-carpentry.org/workshops/index.html

Nothing shows up on map, only 2 workshops show up in calendar for October.

**Comment by gvwilson** [comment]
Aaaarrrgghhh.... @piotr @rgaiacs can you please have a look I'm in a 
workshop all day.

**Comment by gvwilson** [comment]
OK, the map is showing up correctly now (I think), but the calendar is still not showing all the events, which means the workshops.ics file isn't being generated correctly.

**Comment by rgaiacs** [comment]
The iCalendar that we use is at https://software-carpentry.org/workshops.ics.
One of the events are

~~~
BEGIN:VEVENT
UID:2015-10-19-UMich@software-carpentry.org
DTSTAMP:2015-10-22T01:13:08Z
DTSTART;VALUE=DATE:2015-10-19
DTEND;VALUE=DATE:2015-10-21
SUMMARY:University of Michigan
DESCRIPTION;ALTREP="https://umswc.github.io/2015-10-19-UMich/":https://umswc.github.io/2015-10-19-UMich/
URL:https://umswc.github.io/2015-10-19-UMich/
LOCATION:University of Michigan
uGEO:42.283228;-83.733597
END:VEVENT
~~~

Checking the [specification](https://tools.ietf.org/html/rfc5545#section-3.3.4) the `DATE` is not properly formatted. The specification says

> (...) **There are no separator characters between the year, month, and day component text.** (...)
> 
> Example:  The following represents July 14, 1997:
>
>     19970714

The `DATE-TIME` is also wrong:

>  Example:  The following represents July 14, 1997, at 1:30 PM in New York City in each of the three time formats, using the "DTSTART" property.
>
>       DTSTART:19970714T133000
>       DTSTART:19970714T173000Z
>       DTSTART;TZID=America/New_York:19970714T133000

@gvwilson Could you try make this corrections and see if Google are more happy with our iCalendar?

**Comment by gvwilson** [comment]
1. Modified the calendar generation script bin/make-calendar.py to 
format DTSTART and DTEND as YYYYMMDD.
2. Copied the generated file to the website.
3. Forced reload of http://software-carpentry.org/workshops/ in the browser.
4. Calendar is still not showing all events.

Top of workshops.ics now looks like this:

~~~
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Software Carpentry/Workshops//NONSGML v1.0//EN
BEGIN:VEVENT
UID:2016-01-18-leeds@software-carpentry.org
DTSTAMP:2015-10-22T05:14:12Z
DTSTART;VALUE=DATE:20160118
DTEND;VALUE=DATE:20160121
SUMMARY:NERC / University of Leeds
DESCRIPTION;ALTREP="https://andreww.github.io/2016-01-18-leeds/":https://andreww.github.io/2016-01-18-leeds/
URL:https://andreww.github.io/2016-01-18-leeds/
LOCATION:NERC / University of Leeds
uGEO:53.8057;-1.5557
END:VEVENT
BEGIN:VEVENT
UID:2016-01-06-bristol@software-carpentry.org
DTSTAMP:2015-10-22T05:14:12Z
DTSTART;VALUE=DATE:20160106
DTEND;VALUE=DATE:20160109
SUMMARY:NERC / University of Bristol
DESCRIPTION;ALTREP="https://andreww.github.io/2016-01-06-bristol/":https://andreww.github.io/2016-01-06-bristol/
URL:https://andreww.github.io/2016-01-06-bristol/
LOCATION:NERC / University of Bristol
uGEO:51.456;-2.604
END:VEVENT
~~~

**Comment by rgaiacs** [comment]
@gvwilson Thanks for the pull request. Since Google doesn't provide the log is difficult to find what the problem is. I would love to have the calendar created by client-side Javascript since this will solve the problem but I don't know of any library for the job.

**Comment by jduckles** [comment]
Fixed the calendar with #1163 

![Calendar](https://jduckles-dropshare.s3-us-west-2.amazonaws.com/Screen-Shot-2015-11-10-14-20-30.png)

**Comment by gvwilson** [comment]
Excellent - I'm guessing it's the switch to Py3 that introduced that 
errant 'u'.

**Comment by gvwilson** [comment]
@maneesha can you please verify, and then we'll close?

**Comment by pzurek** [comment]
Hey guys, can you please stop using @piotr to refer to whoever is working with you on this? This is one of my GitHub accounts and I get notified about it all the time.

**Comment by rgaiacs** [comment]
@gvwilson you need to use @pbanaszkiewicz instead of `@piotr`.

**Comment by maneesha** [comment]
I think this looks good for now.  However, I want to refer back to some issues in the amy repo:

https://github.com/swcarpentry/amy/issues/562
and
https://github.com/swcarpentry/amy/issues/547

An instructor will create a workshop webpage before the exact location is known, and fill in the location later.  So it won't show on the map.  I don't always know that they've filled in the location later.  It would be good in this case also to have a notification that the github page has been updated so that I can make the change as needed.

**Comment by gvwilson** [comment]
Hm.  You're right, if we're getting data from AMY rather than directly 
from GitHub, and AMY only updates from GitHub when told to, we're going 
to miss changes.  We can't rely on instructors to notify us when they 
make changes to workshop websites (because they'll forget), and I don't 
think there's a way to do push notifications from GitHub on changes, so 
that means AMY will need to poll, just as the SWC web site was polling 
before we started getting info from AMY.

**Comment by gvwilson** [comment]
@pbanaszkiewicz how are we doing to fix this one?

**Comment by pbanaszkiewicz** [comment]
@gvwilson either me or @wking or together – solution probably will require cronjob. See https://github.com/swcarpentry/amy/issues/562#issuecomment-154751990 for details.

**Comment by jiffyclub** [comment]
You *can* get push notifications from GitHub, but you probably wouldn't have anymore luck getting instructors to configure their repos than you do getting them to notify you of changes. https://developer.github.com/webhooks/

**Comment by gvwilson** [comment]
Yeah, we're going to have to poll...
