### ISSUE TITLE
Put links to surveys on workshop tab

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/site#1153]
The assessment committee has put together a few new surveys for us to collect information.

I am suggesting to update and change the formatting of the top of the [http://software-carpentry.org/workshops/index.html](workshop page) so they link to our new surveys.

The surveys should eventually be integrated with the workshop [website template](https://github.com/swcarpentry/workshop-template)

@JasonJWilliamsNY @maneesha

**Comment by gvwilson** [comment]
Relocated to https://github.com/swcarpentry/website/issues/100
