### ISSUE TITLE
site doesn't build

### ISSUE THREAD

**Issue by btel** [swcarpentry/site#1196]
`make site` produces the following error:

```
make[1]: Entering directory `/home/bartosz/repos/websites/swc_site'
python3 ./bin/preprocess.py -c ./config -o /home/bartosz/repos/websites/swc_site/_site -s /home/bartosz/repos/websites/swc_site/_site
Traceback (most recent call last):
  File "./bin/preprocess.py", line 248, in <module>
    main()
  File "./bin/preprocess.py", line 99, in main
    config['blog'] = harvest_blog(config)
  File "./bin/preprocess.py", line 177, in harvest_blog
    decorated.sort()
TypeError: unorderable types: dict() < dict()
```

I am using python 3.4 installed via anaconda.

My investigations showed that the problem is with duplicate date and hours of two blog posts: `blog/2015/11/instructor-debriefing-2015-11-10.html` and  `duplicated in blog/2015/11/postretreat_blogpost.html`. Changing `time` metadata in one of them solves the problem.

**Comment by gvwilson** [comment]
Thanks for the bug report - fixed in 3d0bfab.
