### ISSUE TITLE
Update our reading list

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#1212]
Our reading list is out of date - please propose additions by adding comments to this issue. In order to qualify, an addition must have:

1.  author(s), title, and date (and journal, if a published paper)
2.  link (to amazon.com, publisher's site, or preprint)
3.  short summary similar to those in [the current page](http://software-carpentry.org/bib/reading.html)
4.  one or more tags telling us which lesson(s) the item relates to

Please note that entries won't be included without the summary. Please also note that we strongly prefer open-access materials, but recognize that some useful material (particularly books) is not openly available.

cc @elliewix @LJWilliams

**Comment by marwahaha** [comment]
1. Computational and Inferential Thinking: The Foundations of Data Science
Ani Adhikari, John DeNero
2. http://data8.org/text/
3.  An introductory text for data science. Explores concepts in programming and statistics in Python.
4.  Python, visualization, statistics

(Used for a new class at Berkeley. The interactive buttons won't work, but the text is online.)

**Comment by fpsom** [comment]
1. **"Data integration in biological research: an overview"**, Vasileios Lapatas, Michalis Stefanidakis, Rafael C. Jimenez, Allegra Via and Maria Victoria Schneider, *Journal of Biological Research* (2015)
2. [Open Access article](http://www.jbiolres.com/content/22/1/9)
3. Good practices on how to perform data integration, especially in Life Science data (i.e. bioinformatics approaches). Includes standard formats such as FASTA, FASTq, SAM, GFF etc.
4. Data Carpentry, data organization, data cleaning

**Comment by davidedelvento** [comment]
1. Johnny Lin, A Hands-On Introduction to Using Python in the Atmospheric and Oceanic Sciences (book)
2. http://www.johnny-lin.com/pyintro/
3. This book is a hands-on mini-course on Python written for Atmospheric and Oceanic Sciences (AOS) researchers, graduate students, and advanced undergraduates who are new to Python. It focuses on how Python can help AOS researchers. 
4. Python, visualization, AOS

**Comment by fangohr** [comment]
1. Hans Fangohr, Introduction to Python for Computational Science and Engineering - a beginner's guide  
2. http://www.southampton.ac.uk/~fangohr/training/python/pdfs/Python-for-Computational-Science-and-Engineering.pdf
3. Self-contained text-book (~160pages), aimed at complete beginners. Includes introduction to Python, section on why Python, REPL, introspection, input/output, control flow, functions and modules, functional tools, symbolic calculation, numpy and scripy, visualising data (mostly matplotlib), suggestions for further reading and learning.
4. Learning Python, visualisation, numpy, scipy, symbolic calculations.

The material is used at the University of Southampton and some other academic institutions in the UK and elsewhere to support computing teaching in undergraduate and postgraduate courses. 

Disclaimer: entry submitted by author of the material.

**Comment by chendaniely** [comment]
[Effective Computation in Physics](http://physics.codes/) (it's like "SWC in a book")
It even comes with a [template syllabus](https://github.com/physics-codes/seminar)!

**Comment by LJWilliams** [comment]
Thanks Daniel
