### ISSUE TITLE
Menu iconification in small browser windows

### ISSUE THREAD

**Issue by caen-bennet** [swcarpentry/site#580]
I posted this to the SWC [Discuss] list, and Greg asked that I file a proper bug report.

I had this exchange:

On Mon, Aug 18, 2014 at 11:53 AM, W. Trevor King <wking@tremily.us> wrote:

    > The blog's presence on the main SWC web site seems to me implicit, and
    > if I hadn't spent the last 10 minutes looking around trying to track
    > it down, I would probably still be wondering where it is.

    http://software-carpentry.org/ has a “Blog” link in the navigation
    bar.  That seems pretty standard to me.

which was a bit embarrassing.  As it turns out, the menu iconifies if the browser window is smaller than some defined size.  That renders it effectively invisible to some people.  I am a newcomer, and I filtered the icons existence completely because it is at the top of what looks like a graphical banner.  Picture attached.  It's obvious to those who know to look for it.  It's just white noise to those who don't, and it gets filtered as such.  At least it was to me.

![swc_main](https://cloud.githubusercontent.com/assets/3419728/3960273/277c217e-273c-11e4-8dff-a18727ae8fa1.png)

**Comment by gvwilson** [comment]
@acabunoc was this ever fixed?
