### ISSUE TITLE
Future Workshops not sorted

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#715]
I don't know why but there is a [future workshop](http://software-carpentry.org/workshops/index.html#future) in the wrong position. Instead of

- University of Nebraska-Lincoln: Jan 8-9, 2015
- American Astronomical Society 225th Meeting: Jan 3-4, 2015
- Women in Science and Engineering, University of Colorado: Jan 5-6, 2015
- Women in Science and Engineering, University of Michigan: Jan 5-6, 2015
- Institute of Arctic and Alpine Research (INSTAAR), Room 620: Jan 7-9, 2015
- National Institutes of Health Library: Jan 8-9, 2015

we should have

- American Astronomical Society 225th Meeting: Jan 3-4, 2015
- Women in Science and Engineering, University of Colorado: Jan 5-6, 2015
- Women in Science and Engineering, University of Michigan: Jan 5-6, 2015
- Institute of Arctic and Alpine Research (INSTAAR), Room 620: Jan 7-9, 2015
- University of Nebraska-Lincoln: Jan 8-9, 2015
- National Institutes of Health Library: Jan 8-9, 2015

**Note the change in the position of "University of Nebraska-Lincoln".

![swc](https://cloud.githubusercontent.com/assets/1506457/5604565/7a767b3c-93ab-11e4-9e26-88a94999637c.jpg)

**Comment by gvwilson** [comment]
Yup, I've sent a PR to the workshop's instructors.
G

On 2015-01-03 6:52 PM, Raniere Silva wrote:
>
> I don't know why but there is a future workshop 
> <http://software-carpentry.org/workshops/index.html#future> in the 
> wrong position. Instead of
>
>   * University of Nebraska-Lincoln: Jan 8-9, 2015
>   * American Astronomical Society 225th Meeting: Jan 3-4, 2015
>   * Women in Science and Engineering, University of Colorado: Jan 5-6,
>     2015
>   * Women in Science and Engineering, University of Michigan: Jan 5-6,
>     2015
>   * Institute of Arctic and Alpine Research (INSTAAR), Room 620: Jan
>     7-9, 2015
>   * National Institutes of Health Library: Jan 8-9, 2015
>
> we should have
>
>   * American Astronomical Society 225th Meeting: Jan 3-4, 2015
>   * Women in Science and Engineering, University of Colorado: Jan 5-6,
>     2015
>   * Women in Science and Engineering, University of Michigan: Jan 5-6,
>     2015
>   * Institute of Arctic and Alpine Research (INSTAAR), Room 620: Jan
>     7-9, 2015
>   * University of Nebraska-Lincoln: Jan 8-9, 2015
>   * National Institutes of Health Library: Jan 8-9, 2015
>
> **Note the change in the position of "University of Nebraska-Lincoln".
>
> swc 
> <https://cloud.githubusercontent.com/assets/1506457/5604565/7a767b3c-93ab-11e4-9e26-88a94999637c.jpg>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/715>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by r-gaia-cs** [comment]
I'm closing this as out of date.
