### ISSUE TITLE
ImportError: No module named github

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#716]
I tried to build the site locally but

~~~
$ make cache
cp ./config/workshops_saved.yml ./_workshop_cache.yml
...
Traceback (most recent call last):
  File "bin/make-dashboard.py", line 7, in <module>
    from github import Github
ImportError: No module named github
Makefile:100: recipe for target 'cache' failed
make: *** [cache] Error 1
~~~

and couldn't install `github` package

~~~
$ pip install github
Downloading/unpacking github
  Could not find any downloads that satisfy the requirement github
Cleaning up...
No distributions at all found for github
~~~

@gvwilson Could you take a look on this since this is due b9ce4cb9?

**Comment by gvwilson** [comment]
Fixed in 51902f06a - please run 'pip install -r requirements.txt'
Thanks,
Greg

On 2015-01-03 7:06 PM, Raniere Silva wrote:
>
> I tried to build the site locally but
>
> |$ make cache
> cp ./config/workshops_saved.yml ./_workshop_cache.yml
> ...
> Traceback (most recent call last):
>    File "bin/make-dashboard.py", line 7, in <module>
>      from github import Github
> ImportError: No module named github
> Makefile:100: recipe for target 'cache' failed
> make: *** [cache] Error 1
> |
>
> and couldn't install |github| package
>
> |$ pip install github
> Downloading/unpacking github
>    Could not find any downloads that satisfy the requirement github
> Cleaning up...
> No distributions at all found for github
> |
>
> @gvwilson <https://github.com/gvwilson> Could you take a look on this 
> since this is due b9ce4cb 
> <https://github.com/swcarpentry/site/commit/b9ce4cb9b5247d2650bd14aea13c0912a0c1e243>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/716>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
