### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './git-token.txt'

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#717]
When I tried to build the site locally

~~~
$ make cache site
cp ./config/workshops_saved.yml ./_workshop_cache.yml
...
Traceback (most recent call last):
  File "bin/make-dashboard.py", line 30, in <module>
    with open(token_file, 'r') as reader:
IOError: [Errno 2] No such file or directory: './git-token.txt'
Makefile:100: recipe for target 'cache' failed
make: *** [cache] Error 1
~~~

I believe that `git-token.txt` is the token needed to use GitHub API that is associated with swcarpentry account that that's why it isn't present at this repository. Any workaround?

**Comment by gvwilson** [comment]
You need to create a file with that name containing your own GitHub API 
token.  I apologize for not documenting all of this - the "solution" is 
to have the script run without an API token if one isn't present, but 
throttle its own operation so as not to trip over the limits of 
unauthenticated access.

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by r-gaia-cs** [comment]
@gvwilson I like 1e45a96 and because of it I'm closing this.
