### ISSUE TITLE
Dashboard is empty

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#726]
http://software-carpentry.org/pages/dashboard.html is empty. Probably because the server doesn't have `git-token.txt`.

**Comment by gvwilson** [comment]
It's been fixed - git-token.txt was there, but the Makefile wasn't 
rebuilding the _dashboard_cache.yml file when it needed to.

**Comment by wking** [comment]
How is this dashboard synchronized with GitHub (as issues are
created/closed)?  It might be better to use [1], which gives you the
additional benefit of GitHub's query language [2,3].

[1]: https://github.com/issues?q=is%3Aopen+user%3Aswcarpentry
[2]: https://help.github.com/articles/searching-issues/
[3]: https://help.github.com/articles/search-syntax/
