### ISSUE TITLE
"Recent Comments" display HTML tags in post titles

### ISSUE THREAD

**Issue by embray** [swcarpentry/site#736]
Just noticed that the links to the post titles in this have `<p>` tags around them.

![swc-recent-comments](https://cloud.githubusercontent.com/assets/676149/5770201/feaf3b4e-9cf4-11e4-9409-ab29910d8404.png)

Now that I look, it looks like this was already mentioned in #712 when the feature was first introduced.  Still, seems like it should be fixable, somehow.  I volunteer to look into it when I get a chance.

**Comment by r-gaia-cs** [comment]
> Now that I look, it looks like this was already mentioned in #712 when the feature was first introduced. Still, seems like it should be fixable, somehow. I volunteer to look into it when I get a chance.

@embray Thanks for volunteer to work on this. There isn't very much that we could do. We only get the data that Disqus provide and add it into the page (see `_includes/disqus.html`). I report this problem upstream at https://disqus.com/support/ and hope that they will contact us.

**Comment by dmatt** [comment]
@r-gaia-cs We found that thread titles are being defined by your disqus config variable `disqus_title` as `<p>title</p>`. You may need to change how you are setting those values. More information here: https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables

Screenshot: https://dl.dropboxusercontent.com/spa/o6eo6zi75y2ttog/kzrtf5l7.png

Hope that helps :).

**Comment by fmichonneau** [comment]
I think that replacing:

      var disqus_title = '{{ page.title | textilize }}';

by

    var disqus_title = '{{ page.title }}';

in `_includes/disqus.html` would take care of removing the html tags. I don't know if there are benefits for sanitizing the blog post titles here. It seems that @acabunoc introduced this, could you please elaborate why it's needed?

**Comment by acabunoc** [comment]
@fmichonneau -- I honestly can't remember! You're probably right though?

I'd probably do that if disqus is expecting `disqus_title` to be a string, but that's just a guess.

**Comment by acabunoc** [comment]
Also, it looks like the bug is mentioned in #712, which was before I made that change. So it might not be the right fix after all...

Come to think of it, I probably added it trying to fix this in the first place.

**Comment by fmichonneau** [comment]
OK, thanks @acabunoc. I can't test locally but if @gvwilson can push the latest version of my branch to dev.software-carpentry.org then we can see if that takes care of the problem.

**Comment by acabunoc** [comment]
It doesn't look like this actually fixed the issue:

![image](https://cloud.githubusercontent.com/assets/617994/6447587/a531e740-c0e1-11e4-804c-0de578a47f23.png)


I think this issue should be re-opened.

**Comment by fmichonneau** [comment]
I might be wrong, but my understanding is that the titles being used at the
bottom of the comments here are created when the posts appear online.
Disqus then use them to identify where the comments belong.

The comments on posts that appeared before February 28th (when the changes
were merged) are going to include the html tags, and if the bug is fixed,
comments of posts after that will not include the tags.

**Comment by acabunoc** [comment]
@fmichonneau - running a test now :) Even so, it's best practice to keep an issue open till we have a confirmed fix

**Comment by acabunoc** [comment]
Looks good!

![image](https://cloud.githubusercontent.com/assets/617994/6449036/fbe2cb90-c0eb-11e4-8e6e-0ee32db59c9b.png)

**Comment by fmichonneau** [comment]
Yay! :sunny:
