### ISSUE TITLE
"which frankly" typo and other changes to Adina's nomination post

### ISSUE THREAD

**Issue by wking** [swcarpentry/site#741]
This landed unreviewed in 724006e (More nomination posts, 2015-01-16), but I think “… prowess, which frankly, I didn't possess” should be “… prowess which, frankly, I didn't posess”.

Also, “… to peruse my see my…” should be “… to peruse my…” or “… see my…”.

Do we want to ajust “bootcamp” to “workshop”?  See swcarpentry/bc#240.

“A few of professors…” should be “A few professors…”.

Should “board” be “steering committee”?

CC @adina.

**Comment by gvwilson** [comment]
On 2015-01-17 1:53 PM, W. Trevor King wrote:
>
> This landed unreviewed in 724006e 
> <https://github.com/swcarpentry/site/commit/724006ec43050bbcf5c49c2bb3bc21860197b6ec> 
> (More nomination posts, 2015-01-16), but I think “… prowess, which 
> frankly, I didn't possess” should be “… prowess which, frankly, I 
> didn't posess”.
>
The original is grammatically correct.
>
> Also, “… to peruse my see my…” should be “… to peruse my…” or “… see my…”.
>
Thanks.
>
> Do we want to ajust “bootcamp” to “workshop”? See swcarpentry/bc#240 
> <https://github.com/swcarpentry/bc/issues/240>.
>
The former is historically accurate, but I've changed to the latter to 
be consistent - thanks.
>
> “A few of professors…” should be “A few professors…”.
>
> Should “board” be “steering committee”?
>
THanks,
Greg

**Comment by wking** [comment]
On Sat, Jan 17, 2015 at 11:26:35AM -0800, Greg Wilson wrote:
> On 2015-01-17 1:53 PM, W. Trevor King wrote:
> > This landed unreviewed in 724006e (More nomination posts,
> > 2015-01-16), but I think “… prowess, which frankly, I didn't
> > possess” should be “… prowess which, frankly, I didn't posess”.
>
> The original is grammatically correct.

Maybe we both like “… prowess, which frankly I didn't possess”?  I
think it's just a question of what's being said aside.  Dropping the
whole “which frankly…” phrase would be fine, and dropping just
“frankly” would be fine, but read through and saying just “which
frankly” sotto voce sounds odd.  Anyway, if you and @adina are
comfortable with it how it stands that's enough for me.

**Comment by wking** [comment]
On Sat, Jan 17, 2015 at 12:08:33PM -0800, W. Trevor King wrote:
> Sat, Jan 17, 2015 at 11:26:35AM -0800, Greg Wilson:
> > 2015-01-17 1:53 PM, W. Trevor King:
> > > This landed unreviewed in 724006e (More nomination posts,
> > > 2015-01-16), but I think “… prowess, which frankly, I didn't
> > > possess” should be “… prowess which, frankly, I didn't posess”.
> >
> > The original is grammatically correct.
> 
> Maybe we both like “… prowess, which frankly I didn't possess”?  I
> think it's just a question of what's being said aside.  Dropping the
> whole “which frankly…” phrase would be fine, and dropping just
> “frankly” would be fine, but read through and saying just “which
> frankly” sotto voce sounds odd.  Anyway, if you and @adina are
> comfortable with it how it stands that's enough for me.

Resolved with #742.
