### ISSUE TITLE
Footer not visible at small screens

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#752]
- [ ] 320x480: white text with white background

![screen shot 2015-01-23 at 19 45 16](https://cloud.githubusercontent.com/assets/1506457/5883171/1c4fd17a-a337-11e4-9add-a9eb2c41a4eb.png)

- [ ] 480x320: improve align?

![screen shot 2015-01-23 at 19 46 13](https://cloud.githubusercontent.com/assets/1506457/5883186/38a93f14-a337-11e4-9797-cf3bf0e7f86a.png)

- [ ] 768x1024: white background after the footer

![screen shot 2015-01-23 at 19 47 18](https://cloud.githubusercontent.com/assets/1506457/5883206/611e075e-a337-11e4-84eb-45148d27a227.png)

**Comment by fmichonneau** [comment]
This will be fixed once ec38fb662a24bb43fb1b8f6c2ba4cbc27c96a8d8 is merged.

**Comment by fmichonneau** [comment]
This will be fixed once fmichonneau@styles/ec38fb662a24bb43fb1b8f6c2ba4cbc27c96a8d8 is merged.

**Comment by r-gaia-cs** [comment]
@fmichonneau Thanks. I'm closing this for know.
