### ISSUE TITLE
Google Maps of upcoming and past workshops don't show New Zealand

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#802]
The Google Map display of upcoming workshops on workshops/index.html, and the map on workshops/previous.html, don't show New Zealand by default. They should.

**Comment by r-gaia-cs** [comment]
We also [had one workshop](http://software-carpentry.org/workshops/previous.html) at Hawaii that is only visible if scrolling the map.

![s](https://cloud.githubusercontent.com/assets/1506457/6169576/a4d67606-b2b5-11e4-9bcc-e140b5e73ce1.jpg)

**Comment by gvwilson** [comment]
Aarrghh...

**Comment by timtomch** [comment]
This seems to be a long standing issue for our New Zealand friends... http://worldmapswithout.nz/

**Comment by BernhardKonrad** [comment]
A quick fix would be to play with `zoom` and `center` in `mapOptions` in the three corresponding javascript functions:
https://github.com/swcarpentry/site/blob/master/js/maps.js#L53
https://github.com/swcarpentry/site/blob/master/js/maps.js#L81
https://github.com/swcarpentry/site/blob/master/js/maps.js#L128

**Comment by gvwilson** [comment]
Yes, but what settings would you use?

**Comment by fmichonneau** [comment]
FWIW with the modifications brought by Bootstrap 3, the map is a little larger and with a 1280px wide display, the map shows both Hawaii and New Zealand:

http://dev.software-carpentry.org/workshops/previous.html

**Comment by r-gaia-cs** [comment]
@fmichonneau thanks for migrate our website to Bootstrap3. The map looks great now. :heart:

**Comment by fmichonneau** [comment]
@gvwilson, can we close this now?
