### ISSUE TITLE
Calendar of upcoming events isn't working

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#803]
The calendar on workshops/index.html that's supposed to show upcoming workshops doesn't.

**Comment by josePhoenix** [comment]
For me, I see an empty calendar widget with the message "Events from one or more calendars could not be shown here because you do not have the permission to view them."

**Comment by gvwilson** [comment]
Right - but it used to display all the upcoming workshops. Somewhere, 
the web is broken...

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 12:33:48PM -0800, Joseph Long wrote:
> For me, I see an empty calendar widget with the message "Events from
> one or more calendars could not be shown here because you do not
> have the permission to view them."

When I access the iframe URL (https://www.google.com/calendar/embed?…)
I see that too (after I log into Google).  I'd guess someone made the
backing calendar private, but I know nothing about Google's calendars.

**Comment by gvwilson** [comment]
Closed by 1a5df7c10ef5e9b0bedf63f8af010e9486f7c552

**Comment by wking** [comment]
On Wed, Mar 25, 2015 at 06:43:11AM -0700, Greg Wilson wrote:
> Closed by 1a5df7c10ef5e9b0bedf63f8af010e9486f7c552

Hmm.  Do we know why this worked?  Looking at the diff, I'd guess the
significant change is:

  src=efjc2eea4qegtctcrg6kc0nrba9i0rbg%40import.calendar.google.com

to:

  src=h7t394o5uodii4a18vr8vh6mv0ga4cdq%40import.calendar.google.com

Did you just create a new calendar?

It also looks like you dropped title=Boot%20Camps.  Was that
intentional?

**Comment by gvwilson** [comment]
On 2015-03-25 12:39 PM, W. Trevor King wrote:
> On Wed, Mar 25, 2015 at 06:43:11AM -0700, Greg Wilson wrote:
> > Closed by 1a5df7c10ef5e9b0bedf63f8af010e9486f7c552
>
> Hmm. Do we know why this worked? Looking at the diff, I'd guess the
> significant change is:
>
> src=efjc2eea4qegtctcrg6kc0nrba9i0rbg%40import.calendar.google.com
>
> to:
>
> src=h7t394o5uodii4a18vr8vh6mv0ga4cdq%40import.calendar.google.com
>
> Did you just create a new calendar?
>
Nope - I asked Google Calendar to regenerate the HTML, then pasted that 
in.  No idea why the magic ID would change, but *shrug*
> It also looks like you dropped title=Boot%20Camps. Was that
> intentional?
Yup - looked unnecessary in situ.

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
