### ISSUE TITLE
What project templates (or "cookie cutters") do you use?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#806]
"Cookie cutter" projects are quite common — essentially, they are pre-built templates for project that follow some kind of convention for folder structures and basic boilerplate.  Examples include [cookiecutter](https://github.com/audreyr/cookiecutter) and [Project Template](http://projecttemplate.net/).

For Software Carpentry, it serves as a way for us to teach our attendees some best practices while showing them the importance of reproducibility and scripts. It also allows a low barrier of entry to actually set up a project folder structure, since re-organizing folders when a project is fully developed will most likely not happen.

If you use cookie cutter project templates of some kind, we'd like to hear about them: please add pointers to this GitHub issue or [mail us directly](mailto:gvwilson@software-carpentry.org).

**Comment by ncoghlan** [comment]
Fedora's DevAssistant is another example: http://devassistant.org/

**Comment by rmflight** [comment]
I would argue that for `R`, the `package` is a logical template for a project, as it can easily contain all of the necessary folders required, and provides a mechanism for automatic generation of reports / papers via the `vignette`. @hadley has [a book](http://r-pkgs.had.co.nz/) he is writing on `R` packages, and I have written a couple of blog posts [1](http://rmflight.github.io/posts/2014/07/analyses_as_packages.html) [2](http://rmflight.github.io/posts/2014/07/vignetteAnalysis.html) on how I use packages for organizing data and generating scientific reports.

**Comment by embray** [comment]
The [Astropy](http://www.astropy.org/) project tries to make it easier to set up an [affiliated package](http://www.astropy.org/affiliated/index.html) by providing its own [package template](https://github.com/astropy/package-template) for developers to use to start their project, so that they don't have to think too much about details like high level source code layout, how to set up builds and test frameworks, etc.  It provides most of what a project that works with Astropy will need, including support for things like Cython, though most of it is not very Astropy-specific.  I feel like at the moment it's a little overcomplicated--users clone a GitHub repository and then follow instructions to tweak it for their own project.  At some point if I ever have time I want to port it to a project template framework like [cookiecutter](https://github.com/audreyr/cookiecutter).

**Comment by jduckles** [comment]
I've developed a [cookiecutter](https://github.com/ouinformatics/eoa-cookiecutter) for [Edition Open Access](http://www.edition-open-access.de/) LaTeX docs. Very simple for now, but gets people over the hump to get a directory setup with the appropriate templates.

**Comment by Choens** [comment]
I maintain a project template that I use. In addition to a folder structure, it includes some boilerplate code that makes it easier for me to set up and start a new project:

Project Template: https://github.com/Choens/analytic-template-r
File Templates: https://github.com/Choens/analytic-templates

I keep meaning to add more templates to the file templates, but haven't done so. I might take a look at @jduckles LaTeX templates to see if I could borrow from some of his ideas.

**Comment by sritchie73** [comment]
I had a play with [ProjectTemplate](projecttemplate.net), and incorporating it into a [novice R lesson on projects](resbaz.github.io/novice-r/02-project-intro.html). However, after writing the lesson, it became clear to me that:
 * (a) the directory structure creates was unnecessarily complicated for a novice workshop, and 
 * (b) automates a lot of things (data loading, library calls), which make it hard to teach. 

I ultimately ended up stripped it out, and instead used it as a guide for getting learners to populate a new project with useful subdirectories.

**Comment by hjelmj** [comment]
Don't have much experience with cookie cutters but was looking for such projects last week as
I am interested in standardizing my folder structure for different projects.
At the moment I have a different structure for nearly every project. It is self-inflicted but
very frustrating.

I came across the following two, I find rr-init most appealing, so will try this one out for the next while. 

https://github.com/Reproducible-Science-Curriculum/rr-init

https://github.com/chendaniely/computational-project-cookie-cutter

**Comment by hmgaudecker** [comment]
As a direct result of SWC, I came up with this:

[code] https://github.com/hmgaudecker/econ-project-templates
[tutorial] http://hmgaudecker.github.io/econ-project-templates/

After some initial hiccups, it works well in semester-long courses, in block courses I tend to experience the same as @sritchie73 above.

**Comment by benmarwick** [comment]
+1 to @rmflight's suggestion to use R packages as a project template (for R users). There are several of us doing this, including @cboettig's [template package](https://github.com/cboettig/template), @pakillo's [template package](https://github.com/Pakillo/template) and @jhollist's [manuscriptPackage](https://github.com/jhollist/manuscriptPackage), etc, in addition to Rob's blog posts and @hadley's book on writing packages. 

The concept of an R package as a research compendium has been around for a while in academic literature (cf. [Gentleman 2005](http://www.uvm.edu/~pdodds/files/papers/others/everything/gentleman2005a.pdf), [Gentleman & Temple Lang 2007](http://www.researchgate.net/profile/Duncan_Temple_Lang/publication/40823095_Statistical_Analyses_and_Reproducible_Research/links/0deec5356feeec36e2000000.pdf)), so there is some wider familiarity with R packages for a project structure already. 

There are still a bunch of open questions on how best to use the R package structure (https://github.com/ropensci/unconf/issues/11), so it might be more of an intermediate/advanced lesson for people already comfortable with R.

**Comment by sritchie73** [comment]
Personally I wouldn't use R packages as a project template. R packages are
specifically designed for sharing methodology, and trying to shoehorn
analysis pipelines/workflows into that structure doesn't quite work (at
least for me): Scientific analysis is different to software development.

I posted this in a similar SWC email thread a while back, but take a look
at http://projecttemplate.net/ (another R package). I haven;t used it (yet)
but it looks quite useful!

**Comment by rmflight** [comment]
@sritchie73 but R packages have all the pieces needed for a project, given functions (/R), metadata (DESCRIPTION), data (inst/data), short-form documentation (/man), and long-form documentation / analyses (/vignettes), and the ability to add whatever data / folder structure you want under /inst, that will be path agnostic after installing. I would argue that most actual analyses should be structured as vignettes or R-markdown files, because the computation should be embedded in the prose. 

But, for the sake of this thread, I'll stop there.

**Comment by benmarwick** [comment]
ProjectTemplate looks interesting, but I think too complicated, labor intensive, and idiosyncratic to be a generic solution, as @rmflight details in his [comparison of packages vs. ProjectTemplate](http://rmflight.github.io/posts/2014/07/zpackages_vs_projectTemplate.html). I agree that R packages are not ideal for bundling a research project, but they are probably the best current option, having the  advantages of (1) being ubiquitous among R users, (2) having extensive online support and documentation, and (3) in wide use as research repositories already. 

Here's another project structure template, this one is from Christopher Gandrud's book [Reproducible Research with R and RStudio](https://github.com/christophergandrud/Rep-Res-Book) (very cool that the entire book can be reproduced!):
 
![image](https://cloud.githubusercontent.com/assets/1262179/6377448/f41267fc-bcd8-11e4-91e1-68fd35c6b77b.png)

Perhaps the best thing we can do for the SWC novice learner is introduce the general principles of being organised in a research project with, at minimum, a readme plain text file and separate directories for code, data and output, then briefly survey some of the healthy diversity of options that exist for helping with this, and invite learners to find the one that suits them best.

**Comment by wking** [comment]
On Wed, Feb 25, 2015 at 10:53:23AM -0800, Ben Marwick wrote:
> Perhaps the best thing we can do for the SWC novice learner is
> introduce the general principles of being organised in a research
> project with, at minimum, a readme plain text file and separate
> directories for code, data and output, then briefly survey some of
> the healthy diversity of options that exist for helping with this,
> and invite learners to find the one that suits them best.

For example, we could just expore the repository they downloaded for
the workshop (with example filesystems, data, scripts, …).  That's
going to come with the usual README.md, LICENSE.md, tools/, data/,
img/, ….  We can hit a few of those, explain why they're useful, and
then say that the exact organization chosen doesn't really matter, but
that a README*, COPYING/LICENSE.md, and having some sort of organizing
directory structure are almost universal conventions that are worth
following.

**Comment by dfalster** [comment]
This is an important topic to cover, especially for new users who have files (input/output) and scripts all jumbled in together. @richfitz and I wrote a post on "Designing projects" on our blog, http://nicercode.github.io/blog/2013-04-05-projects/. While this stuff may seem elementary to some, it proved [surprisingly popular]((https://twitter.com/search?q=nicercode.github.io%2Fblog%2F2013-04-05-projects%2F).

**Comment by dfalster** [comment]
And here is a followup from one of student's showing how the layout of her project changed by following some simple advice, http://nicercode.github.io/blog/2013-05-17-organising-my-project/

Before:

![before](http://nicercode.github.io/images/2013-05-17-organising-my-project/directory1_before.png)

After:

![after](http://nicercode.github.io/images/2013-05-17-organising-my-project/directory_after.png)
