### ISSUE TITLE
`team.html` shows always one bio

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/site#807]
I was updating my bio and, when testing the changes, found that the `team.html` page shows only Joshua Adelman's bio & picture for each and every instructor. 

I tried to find the bug (if any), but couldn't find how the `team.html` page is built.

This is how to reproduce the issue:

- Checkout master at 92cea88
- `make clean`
- `make site`
- open `_site/pages/team.html` and get ready for multiple Joshuas.

Can someone try to reproduce this? Maybe it's just me doing something wrong.

**Comment by gvwilson** [comment]
Hm - it's working fine for me, and working on the main server.  What 
version of Jekyll do you have?  And after the build, if you look in 
`_config.yml`, you should find a key "people:" (it's the only occurrence 
of that word with no spaces before it on the line).  Can you please 
check that it's a list of all the .html files in the _includes/people 
directory?

**Comment by iglpdc** [comment]
I know it's weird, but I tried twice and got the same...

In `_config.yml` searching for `^people` gives me a long list with probably everyone:

`people: [people/adelman.joshua.html, people/ahmadia.a.html, (many lines) ....]`

My jekyll is 1.3.0.

**Comment by gvwilson** [comment]
Ah - we're using 2.4.0.  Upgrade and re-try?

**Comment by iglpdc** [comment]
Ok, I upgraded to jekyll 2.5.3 and it's working now. So, for the record, if you have an old jekyll, you may need to update.

Closing this.

**Comment by gvwilson** [comment]
Can you please PR a note to README.md explaining the symptom and the 
version needed?

**Comment by iglpdc** [comment]
Sorry, I didn't find the time to do this. I've just seen that in the "More advanced users" section there is a note saying that Jekyll 2.5 is needed. Is there a reason why is not needed for all users? Otherwise we should move this up, to the end of setting up, and require Jekyll 2.5 for everyone. 

@gvwilson Can you confirm whether this is true? I can do the PR afterward.

**Comment by gvwilson** [comment]
Hi @iglpdc - that's sloppy grammar on my part.  Everyone will need the right version of Jekyll, so the note about the version should go much higher up in the page.
