### ISSUE TITLE
PyCon 2015

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#820]
Please use this issue for discussion of meetups and what-not at PyCon 2015 in Montreal.

**Comment by jameshiebert** [comment]
I'll be staying at PyCon through the code sprint. Even if we don't do a workshop, some of us could get together and try and knock off as many GitHub issues as we can.

**Comment by tpoisot** [comment]
Here are a few possible locations:

1. [QCBS] (the local biodiversity research  center) -- they already organized a bootcamp (last year?), and I talked to some of the students representatives that were keen on doing a second one
2. [Calcul Québec][cq] (the HPC center for Québec) -- they have a few locations in Montréal, and it would make sense that they support a swcarpentry bootcamp
3. I can also try to get a room with wireless access for two days at the Université de Montréal (assuming I can get one at no cost)

[QCBS]: http://qcbs.ca/
[cq]: http://www.calculquebec.ca/en/

**Comment by qjcg** [comment]
I'll also be attending PyCon this year, and participating in a workshop and/or code sprint both sound good to me.

Also, @tpoisot : I know someone in the math department at UQAM who expressed some interest in organizing a bootcamp in the past---I'll check in with him and follow up here if there's any news.

**Comment by ttiimm** [comment]
I attended the 'How to Teach Programming' workshop @gvwilson put on last year at the conference.

I'd be interested in grabbing coffee or lunch with any educator(s) who could give me some opinions about learning more about teaching as well as CS education in New England.

If anyone is interested, I'll be around for the conference this weekend.
