### ISSUE TITLE
Unix shell motivation link broken

### ISSUE THREAD

**Issue by moorepants** [swcarpentry/site#827]
One this page:

http://swcarpentry.github.io/shell-novice/

Link:

http://swcarpentry.github.io/shell-novice/motivation.html

**Comment by wking** [comment]
On Mon, Feb 16, 2015 at 05:52:33PM -0800, Jason K. Moore wrote:
> One this page:
> 
> http://swcarpentry.github.io/shell-novice/
> 
> Link:
> 
> http://swcarpentry.github.io/shell-novice/motivation.html

Duplicate of swcarpentry/shell-novice#47?

**Comment by r-gaia-cs** [comment]
> Duplicate of swcarpentry/shell-novice#47?

Yes. I'm closing this as duplicated.
