### ISSUE TITLE
Informe number of instructors at request form

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#839]
If I, Raniere, was filling the [our form](software-carpentry.org/workshops/request.html) will be nice to know in advance how many instructors expenses I will need to cover. So, instead of

> **Approximate number of attendees**
>
> This number doesn't need to be precise. It will help us decide how many instructors your workshop will need.
> 
> - [ ] 25 - 50
> - [ ] 50 - 80
> - [ ] 80+ 

I will write

> **Approximate number of attendees**
>
> This number doesn't need to be precise. It will help us decide how many instructors your workshop will need.
> 
> - [ ] 25 - 50 (around 3 instructors)
> - [ ] 50 - 80 (around 6 instructors)
> - [ ] 80+ (more than 6 instructors)

**Comment by jiffyclub** [comment]
+1

**Comment by gvwilson** [comment]
See #838.
