### ISSUE TITLE
Improve question about expenses and fees at request form

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#840]
Instead of

> My institution will cover instructors' travel and accommodation costs, and I understand the Software Carpentry Foundation's administrative fee structure.
>
> [ ] Yes
> [ ] No

I suggest

> My institution can cover instructors' travel and accommodation costs.
>
> [ ] Yes
> [ ] No (we will send a few suggestion of how you can cover this costs)
>
> My institution will cover Software Carpentry Foundation's administrative fee structure.
>
> [ ] Yes
> [ ] Yes, **but need fees**. In this case, please use the text box at the end of this request to talk about you and your attendees.

**Comment by JasonJWilliamsNY** [comment]
I would write as:


As host, I agree that my institution will cover instructors' travel and accommodation costs;

[ ] Yes
[ ] No

Select which of the following applies to your payment for the administrative fee;

[ ] Full Fee (due prior to workshop): $1250 US

[ ] No Fee: My institution is a Software Carpentry Affiliate/Partner:$0 US (do I qualify?) [link to explanation and partner list]

[ ] Multiple Workshop Reduced Fee: $750 US (do I qualify?) [link to explanation]

[ ] Reduced Fee (for charitable groups, extreme financial hardships ): $ 0-500 US (do I qualify?) [link to explanation]

[ ] Self-organized workshop: $0 (do I qualify?) [link to explanation]

**Comment by jiffyclub** [comment]
+1 for @JasonJWilliamsNY's structuring. I think having the links our to explanations are really helpful, and listing everything let's people know what the spectrum of options are.

**Comment by r-gaia-cs** [comment]
I'm closing this since it was addressed at #838. Check http://software-carpentry.org/workshops/request.html.
