### ISSUE TITLE
GitHub ribbon at workshops/index.html

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#846]
When testing the changes from @fmichonneau there is no GitHub ribbon at
workshops/index.html.

![s](https://cloud.githubusercontent.com/assets/1506457/6321708/6fd7ccc2-bae2-11e4-92a1-1bf16b39c298.jpg)

**Comment by fmichonneau** [comment]
Thanks for the reports @r-gaia-cs ! 

I pushed fixes to my branches for this bug as well as #844 and #845

**Comment by gvwilson** [comment]
Pushing to http://dev.software-carpentry.org right now...
Thanks
Greg

**Comment by r-gaia-cs** [comment]
@fmichonneau http://dev.software-carpentry.org/workshops/previous.html doesn't have GitHub ribbon.

**Comment by fmichonneau** [comment]
Thanks. Fixed in my branch.
