### ISSUE TITLE
Move "Intructor training" to the top at pages/join.html

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#847]
At http://software-carpentry.org/pages/join.html, "Instructor Training" is the last section. I like to suggest that it be the first one.

**Comment by gvwilson** [comment]
Instructor training is full for the rest of this year, so I want to 
de-emphasize it.

**Comment by r-gaia-cs** [comment]
> Instructor training is full for the rest of this year, so I want to
> de-emphasize it.

OK. This sounds reasonable to me.
