### ISSUE TITLE
Need another blog post about Google Summer of Code

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#855]
> Congratulations!
>
> Your Organization Application for NumFOCUS to Google Summer of Code 2015  has been accepted. Your organization's information will be auto-populated  from your Organization profile onto our Participating Organizations page.  Please click  http://www.google-melange.com/gsoc/org/profile/edit/google/gsoc2015/numfocus  if you want to modify your Organization profile. We recommend you take time  to review your profile carefully and add relevant information and links for  the students where applicable.
>
> If you have questions about items on this profile we would recommend you  read over the Melange User's Guide's section titled "Our organization was accepted! How do I create my organization homepage?"
>
> Please be aware the your organization's information is now available to  students, so you should expect to get contact from potential applicants  very soon. If you have any questions, please email Carol Smith directly at  ..., but generally, you are off to the races. Student  applications formally open on 16 March at 19:00 UTC.

**Comment by wking** [comment]
On Mon, Mar 02, 2015 at 11:56:24AM -0800, Raniere Silva wrote:
> > please email Carol Smith directly at ...

I redacted them email address, since it's generally bad form to post
email addresses in the clear without permission ;).

**Comment by r-gaia-cs** [comment]
> I redacted the email address, since it's generally bad form to post email addresses in the clear without permission ;).

Thanks.
