### ISSUE TITLE
Possible confusion about core topics?

### ISSUE THREAD

**Issue by daisieh** [swcarpentry/site#868]
On the page http://software-carpentry.org/workshops/operations.html in the "What makes a workshop a Software Carpentry workshop?" box, it says that a Software Carpentry workshop must cover 

* automation, 
* modular programming, 
* unit testing, and 
* version control, 

but in the FAQ (http://software-carpentry.org/faq.html#core-topics), it says that the core topics must be covered and are 

* automating tasks using the Unix shell; 
* structured programming in Python, R, or MATLAB; 
* version control using Git or Mercurial; and 
* data management using SQL.

Is this supposed to be the same list, or two separate lists, both of which should be covered by all workshops?

**Comment by gvwilson** [comment]
Good catch - the second list is correct.  I'll fix.
Thanks,
Greg

On 2015-03-08 5:06 PM, Daisie Huang wrote:
>
> On the page http://software-carpentry.org/workshops/operations.html in 
> the "What makes a workshop a Software Carpentry workshop?" box, it 
> says that a Software Carpentry workshop must cover automation, modular 
> programming, unit testing, and version control, but in the FAQ 
> (http://software-carpentry.org/faq.html#core-topics), it says that the 
> core topics must be covered and are "automating tasks using the Unix 
> shell; structured programming in Python, R, or MATLAB; version control 
> using Git or Mercurial; and data management using SQL." Is this 
> supposed to be the same list, or two separate lists, both of which 
> should be covered by all workshops?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/868>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
