### ISSUE TITLE
Linking to non-standard lessons

### ISSUE THREAD

**Issue by wking** [swcarpentry/site#870]
@daisieh floated the idea [on discuss@][1] of making alternatives to the standard lessons more discoverable.  I [recommend][2] linking to popular external lessons from our [lessons list][3] and then [removing any lessons that aren't actively maintained][4].  For “aren't actively maintained”, that I'd say “the lesson fails a [validator check][5] or has some other serious longstanding issue which the maintainer has not moved to address in the last six months” or some gut call along those lines.

[1]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002763.html
[2]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002767.html
[3]: http://software-carpentry.org/lessons.html
[4]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002775.html
[5]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py

**Comment by daisieh** [comment]
I would love this: it is very hard for new instructors (and maybe older ones too, I don't know) to find anything that is not in the top of the list of repositories. Software Carpentry has the paradox-of-choice problem going on, where the amount of material is overwhelming!

**Comment by jiffyclub** [comment]
One difficulty with linking from http://software-carpentry.org/lessons.html is that we need to differentiate lessons on the same topic and explain somehow why there are two Git lessons and how they differ. The current format doesn't support that.

**Comment by wking** [comment]
On Tue, Mar 10, 2015 at 11:05:59AM -0700, Matt Davis wrote:
> One difficulty with linking from
> http://software-carpentry.org/lessons.html is that we need to
> differentiate lessons on the same topic and explain somehow why
> there are two Git lessons and how they differ. The current format
> doesn't support that.

I'm fine linking from http://software-carpentry.org/lessons.html to a
separate page of alternatives that goes into these distinctions in
more detail.  I'm also fine managing this list somewhere else, if
that's easier, but we should link from the canonical lessons to the
alternative list, wherever it ends up.

**Comment by wking** [comment]
As an existing example of this sort of thing, we have the core
swcarpentry/python-novice-inflammation [1] and the alternative
swcarpentry/python-novice-turtles [2].  I'm not sure who (if anyone)
is maintaining the turtle version.  The initial push into turtle-ness
was by @gvwilson in swcarpentry/python-novice-turtles@767bc2d7c6
(First part of lesson on Python with turtles, 2014-12-08).

[1]: https://github.com/swcarpentry/python-novice-inflammation
[2]: https://github.com/swcarpentry/python-novice-turtles

**Comment by gvwilson** [comment]
Is http://software-carpentry.org/lessons/ good enough?
