### ISSUE TITLE
Make sponsors more findable

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#882]
Is a little difficult to find http://software-carpentry.org/pages/sponsors.html.

**Comment by gvwilson** [comment]
Yes, and that page needs a complete overhaul - @katyhuff suggested that 
the sponsors go on the main http://software-carpentry.org/scf/index.html 
page.  Just needs hours (or a volunteer).

On 2015-03-17 6:54 AM, Raniere Silva wrote:
>
> Is a little difficult to find 
> http://software-carpentry.org/pages/sponsors.html.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/site/issues/882>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by gvwilson** [comment]
Check the new http://software-carpentry.org/scf/supporters.html and the sidebar on the home page and let me know.

**Comment by r-gaia-cs** [comment]
Looks good to me.
