### ISSUE TITLE
Split sponsors by year

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#883]
Maybe split http://software-carpentry.org/pages/sponsors.html by year?

**Comment by gvwilson** [comment]
Check the new http://software-carpentry.org/scf/supporters.html page and let me know.

**Comment by r-gaia-cs** [comment]
@gvwilson can you reassign this to someone else? I can't do this in the next two weeks (due GSoC stuffs).

**Comment by r-gaia-cs** [comment]
Looks good to me.
