### ISSUE TITLE
new FAQ: "Why do we call students lerners?" 

### ISSUE THREAD

**Issue by dlebauer** [swcarpentry/site#884]
Presumably this is in reference to a pedagogical principle. If so, this could be explained in the FAQ. 

If it is more an obscure Sci-fi reference (Vader to Obi-wan: "When I left you, I was but the learner; now I am the master."), also should be mentioned.

If the two options are related (e.g. The pedagogical principle overlaps with Jedi training), that too could be explained.

**Comment by wking** [comment]
On Tue, Mar 17, 2015 at 09:45:02AM -0700, David LeBauer wrote:
> Presumably this is in reference to a pedagogical principle. If so,
> this could be explained in the FAQ.

Previous comments on this choice starting at [1].

[1]: https://github.com/swcarpentry/workshop-template/pull/89#issuecomment-67718126

**Comment by dlebauer** [comment]
resolved in #884

**Comment by wking** [comment]
On Tue, Mar 17, 2015 at 10:25:02AM -0700, David LeBauer wrote:
> resolved in #884

This is #884 ;).  I think you meant “resolved in #885”.

**Comment by dlebauer** [comment]
> This is #884 ;).  I think you meant “resolved in #885”.

yep! fixed
