### ISSUE TITLE
Additional additional references to "how to acknowledge" section of FAQ

### ISSUE THREAD

**Issue by dlebauer** [swcarpentry/site#890]
In the "How to Acknowledge" section of the faq, could also add links to Wilson et al 2013 and Wilson 2014 as appropriate;

Also, there are a number of more recent mentions in the popular press. I already added one to Nature news in pull request #887. Another good one might be from [Library Journal](http://lj.libraryjournal.com/2014/09/opinion/not-dead-yet/connecting-researchers-to-new-digital-tools-not-dead-yet/)

Rather than filling up the faq, perhaps these lists could be maintained under a "News" and/or "Publications" page for references and news mentions (and the faq could point there).

**Comment by gvwilson** [comment]
There's a file in the root directory called `CITATION` - where should we put a link referring to it?

**Comment by dlebauer** [comment]
Line 335 of [faq.html](https://github.com/swcarpentry/site/blob/master/faq.html) "also see [CITATION.md](https://github.com/swcarpentry/site/blob/master/CITATION.md)" ... I'd submit a PR but am on a mobile device right now
