### ISSUE TITLE
Workshop request form need description for self-organized workshop

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#894]
The form has

> No fee (self-organized workshop)

it should be more meaningful for someone requesting a workshop. My suggestion is

> No fee (I already have a agreement with the instructors)

**Comment by gvwilson** [comment]
:+1: - what other changes should we make to the form based on what we know now? @apawlik @karinlag ?

**Comment by amyrbrown** [comment]
We need an option for a first workshop at a for-profit, and a second workshop at a for-profit. And while we're at it I think we should change the wording and make sure the non-profit fees are clearer. I suggest:

Full fee for first workshop in the calendar year (non-profit) (US$1250)
Reduced fee for subsequent workshop in the same year (non-profit) (US$750) 
Full fee for first workshop in the calendar year (for-profit) (US$5000)
Reduced fee for subsequent workshop in the same year (for-profit) (US$3000)

**Comment by gvwilson** [comment]
Fixed in 70202c7
