### ISSUE TITLE
Foundation subcommittees page?

### ISSUE THREAD

**Issue by amyrbrown** [swcarpentry/site#908]
Should we have a page listing the SCF subcommittees and members? I always end up looking at this [blog post](http://software-carpentry.org/blog/2015/03/scf-subcommittees.html), but that doesn't seem right. 

Also should we have something about subcommittees in the "[Join](http://software-carpentry.org/pages/join.html)" page?

**Comment by jiffyclub** [comment]
I think we are working on (or have made) a page for subcommittees, though I don't know the link.

I think we should leave subcommittee info off the "Join" page because they are kind of by-invitation-only.

**Comment by amyrbrown** [comment]
Okay, cool. I couldn't find it after some poking around, but I guess at some point it will appear under the "Foundation" page.

Who is responsible for website design/maintenance under the new structure? Still Greg?

**Comment by jiffyclub** [comment]
Still Greg.

**Comment by gvwilson** [comment]
Yup, still Greg.  It shows, doesn't it? :-)

**Comment by amyrbrown** [comment]
I don't know what you mean! It's lovely! :)

**Comment by wking** [comment]
On Mon, Mar 30, 2015 at 01:57:23PM -0700, Matt Davis wrote:
> I think we are working on (or have made) a page for subcommittees,
> though I don't know the link.

List is here [1].  See earlier discussion in swcarpentry/board#18.

[1]: https://github.com/swcarpentry/board/blob/master/subcommittees/subcommittees.md

**Comment by amyrbrown** [comment]
Thanks, @wking, that's perfect! I hadn't poked around the board repo yet. So much content! >_<
