### ISSUE TITLE
Badge metadata isn't provided

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/site#928]
The **very short** explanation of how open badges works is

1. You published your badge at your web page.
2. Your visitor can verify your badge by checking the metadata.

Some time ago if you go to http://software-carpentry.org/badges/creator.html and click on one of the names you get a pop-up with the badge's metadata. Right now the pop-up isn't visible.

AFAICT the problem is due CSS. If I remove `hide` from the `class` of

~~~
<div class="modal fade in" aria-hidden="false" style="padding-right: 13px; display: block;" id="assertion-modal" role="dialog">
~~~

I got

![s](https://cloud.githubusercontent.com/assets/1506457/7104194/2c860248-e0a5-11e4-9ecc-9f148195fc16.jpg)

Is possible that this is also related with changes from http://beta.openbadges.org/issuer.js so I will recommend use a local copy.

@adina Could you check if someone from the Communication Subcommittee could help with that?
I can only fix this at the end of the month.

**Comment by r-gaia-cs** [comment]
@gvwilson Someone change the behavior of the links at the pages listing the badges that we had issue. Now the links goes to the team page instead of show the badge. Can you give me a update on this?

**Comment by gvwilson** [comment]
We're no longer producing or serving digital badges, and nobody's noticed or complained.
