### ISSUE TITLE
Git on Mac Instructions are out of date

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/site#931]
Our instructions at https://software-carpentry.org/v5/setup.html are directing users of Mac OS 10.8 to download the wrong Git installer.

People with Mac OS 10.9 or greater should be directed to http://git-scm.com/download/mac to get the latest "mavericks" download.

People with Mac OS 10.8 or earlier should be directed to download a "snow-leopard" installer from http://sourceforge.net/projects/git-osx-installer/files/.

This relates to the discussion in swcarpentry/workshop-template#196.

**Comment by jiffyclub** [comment]
For anyone unsure where the setup instructions live, they are at https://github.com/swcarpentry/site/blob/master/workshops/setup.html.

**Comment by wking** [comment]
On Mon, Apr 13, 2015 at 01:52:10PM -0700, Matt Davis wrote:
> For anyone unsure where the setup instructions live, they are at
> https://github.com/swcarpentry/site/blob/master/workshops/setup.html.

Why are we duplicating these instructions here instead of just
pointing folks at [1]?  It seems like an increased maintenance cost,
and I don't see an upside…

[1]: https://swcarpentry.github.io/workshop-template/#setup

**Comment by jiffyclub** [comment]
Thanks @wking, I looked all over for the setup instructions and found these ones first. The instructions in the [workshop-template](https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html) repo are also wrong.

**Comment by r-gaia-cs** [comment]
@jiffyclub I think that I can copy https://github.com/swcarpentry/workshop-template/pull/204 to https://software-carpentry.org/v5/setup.html.

**Comment by r-gaia-cs** [comment]
@jiffyclub https://software-carpentry.org/v5/setup.html is based on https://github.com/swcarpentry/bc/.

@gvwilson We should change https://github.com/swcarpentry/bc/blob/gh-pages/setup.md or we can close this as "won't fix"?

**Comment by gvwilson** [comment]
I don't know enough to make the call - you tell me.

**Comment by r-gaia-cs** [comment]
I prefer to just replace

> This is what we currently teach, broken out into one lesson per repository. You can check the status of each lesson on our dashboard, or view the nightly build. 

to

> This is what we currently teach, broken out into one lesson per repository.
> 
> If you are planing to follow the lessons by your own you **must** follow the instructions here to setup your machine.
>
> You can check the status of each lesson on our dashboard, or view the nightly build.

at http://software-carpentry.org/lessons.html.

**Comment by jiffyclub** [comment]
https://software-carpentry.org/v5/setup.html should definitely be kept up-to-date, so please do copy the update over.

**Comment by fmichonneau** [comment]
I agree that it would be nice to have duplicated setup instructions between the workshop template and the website but I'm not sure how we can do this easily.

The workshop-template instructions also includes other info about the workshop. If we just isolate them on their own page, it means that people setting up workshop websites will need to update 2 pages (one for the info about the workshop and one to comment out the software that don't need to be installed).

Does anybody have a better idea than duplicating the content?

**Comment by r-gaia-cs** [comment]
@jiffyclub and @gvwilson What about every lesson have a file `setup.md` with the setup instructions and we update the default setups from the workshop page and site based on that?

**Comment by gvwilson** [comment]
Manual copying of information from place to place hasn't worked well for 
us in the past...  Or are you thinking of automating this somehow?

**Comment by fmichonneau** [comment]
I like @r-gaia-cs's idea but it would be nice to make sure that people setting up workshop websites have the possibility of adding other information for their particular workshop.

**Comment by r-gaia-cs** [comment]
> Manual copying of information from place to place hasn't worked well for
us in the past...  Or are you thinking of automating this somehow?

I'm thinking in have a script to fetch https://raw.githubusercontent.com/swcarpentry/shell-novice/gh-pages/setup.md, https://raw.githubusercontent.com/swcarpentry/git-novice/gh-pages/setup.md, ... and create https://github.com/swcarpentry/workshop-template/tree/gh-pages/_includes/setup.html.

Leader instructors will to edit two files: https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html and https://github.com/swcarpentry/workshop-template/tree/gh-pages/_includes/setup.html.

**Comment by fmichonneau** [comment]
I'm +1 on this. Let me know when you have a prototype ready for review.

I think having the setup instructions associated with each lesson will work better.

**Comment by jiffyclub** [comment]
The setup instructions referenced in the original issue have moved to https://software-carpentry.org/workshops/setup.html but are still wrong for Git/Mac OS X and need to be updated. The instructions on http://swcarpentry.github.io/workshop-template/ are correct, via swcarpentry/workshop-template#204. @rgaiacs do you still want to copy the change over or shall I?

**Comment by rgaiacs** [comment]
> @rgaiacs do you still want to copy the change over or shall I?

Please go ahead and copy the change over.
