### ISSUE TITLE
Same look for future and past workshop maps

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/site#959]
@msarahan Could you send a pull request to change the map on http://software-carpentry.org/workshops/index.html so it have the same look as http://software-carpentry.org/workshops/previous.html?

**Comment by msarahan** [comment]
Yes, this will be a quick fix.

**Comment by msarahan** [comment]
#962

**Comment by r-gaia-cs** [comment]
#962 already merged. I'm closing this.

@msarahan thanks a lot for the fast reply and the pull request. :sparkles:
