### ISSUE TITLE
Some remaining use of bootcamp

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/site#986]
Not sure if this is the right place, but I am about to send around the post-workshop participant survey, and it mentions 'bootcamp' in several places, rather than 'workshop'.

**Comment by r-gaia-cs** [comment]
> Not sure if this is the right place

Any place is right for feedbacks. =)

> but I am about to send around the post-workshop participant survey, and it mentions 'bootcamp' in several places, rather than 'workshop'.

@gvwilson, @apawlik, @amyrbrown Could you fix it?

**Comment by amyrbrown** [comment]
I actually already fixed this one: https://docs.google.com/forms/d/1ioqta6PrK9ULFLJjBTAkzqPWPJL1Pjlsmz9AshReXsA/edit  Are you using a different file, or an older version? (Not sure how Google Drive handles versions.)

**Comment by lexnederbragt** [comment]
On 09 Jun 2015, at 17:26, Amy Brown <notifications@github.com> wrote:
> 
> I actually already fixed this one: https://docs.google.com/forms/d/1ioqta6PrK9ULFLJjBTAkzqPWPJL1Pjlsmz9AshReXsA/edit <https://docs.google.com/forms/d/1ioqta6PrK9ULFLJjBTAkzqPWPJL1Pjlsmz9AshReXsA/edit> Are you using a different file, or an older version? (Not sure how Google Drive handles versions.)
> 

I was sent this one:

https://docs.google.com/forms/d/1HGRTlE0Y_jFqORcmVS0r8fE0UOX2o8nSlOJEeRfhKrU/edit?usp=sharing_eid <https://docs.google.com/forms/d/1HGRTlE0Y_jFqORcmVS0r8fE0UOX2o8nSlOJEeRfhKrU/edit?usp=sharing_eid>

	Lex

**Comment by amyrbrown** [comment]
Oh, okay, that's a survey specifically for the Oslo workshop which someone created from the template file before I changed it. Sorry about that. From now on new surveys should be correct.

**Comment by lexnederbragt** [comment]
Got it. Thanks!

	Lex
