### ISSUE TITLE
Reduce spacing after page title

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#992]
There is too much empty vertical space beneath the page title ("Our Supporters" in the screenshot below).
![screen shot 2015-06-10 at 5 20 56 pm](https://cloud.githubusercontent.com/assets/911566/8094432/2388d4da-0f95-11e5-8417-4d319179273e.png)

**Comment by fmichonneau** [comment]
can you please propose the change here: https://github.com/swcarpentry/styles ? Thanks!
